### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by barrydegraaff** [privacyidea/privacyidea-ldap-proxy#50]
It looks like privacyidea-ldap-proxy is based on Python 2. Are there any plans to port it to Python 3?

**Comment by plettich** [comment]
Hi,
we are currently working on the privacyIDEA code to get it working with Python 3. If that works well, we will focus on the plugins.

**Comment by fredreichbier** [comment]
Adding to that: The LDAP proxy is implemented using Twisted and ldaptor, which both are currently being ported to Python 3, and I'm not sure about the current status.

**Comment by iomarmochtar** [comment]
You can consider to use ldapjs (node library) for proxify the ldap request, i have use it several times as backend for service that doesn't have authentication backend except ldap protocol.

**Comment by lheckemann** [comment]
Both privacyIDEA and ldaptor now support python 3. Has anyone done any work on porting privacyidea-ldap-proxy as well?

**Comment by cornelinux** [comment]
This is done by the PR #54
