### ISSUE TITLE
ldap proxy multi value in search result

### ISSUE THREAD

**Issue by volga629-1** [privacyidea/privacyidea-ldap-proxy#53]
Hello Everyone,
I am trying setup ldap proxy with multi domain environment where users login based on mail  attribute  in ldap server.
I posted detailed report in forum 

https://community.privacyidea.org/t/ldap-proxy-multi-domain/1480

Please any help thank you.

**Comment by cornelinux** [comment]
Integration help is correctly located in the forum, not here at github.
Closing this issue.

**Comment by volga629-1** [comment]
That not integration problem, please read report. That seems like a bug where are ldap proxy can't work with ldap accounts where multiply mail attributes is set. I asked in forum 3 month ago and was no reply to the issue.

Thank you volga629
